export const eventTypes = {
  FETCH_EVENTS_START: "FETCH_EVENTS_START",
  FETCH_EVENTS_SUCCESS: "FETCH_EVENTS_SUCCESS",
  FETCH_EVENTS_FAILURE: "FETCH_EVENTS_FAILURE",
  FETCH_USER_EVENTS_START: "FETCH_USER_EVENTS_START",
  FETCH_USER_EVENTS_SUCCESS: "FETCH_USER_EVENTS_SUCCESS",
  FETCH_USER_EVENTS_FAILURE: "FETCH_USER_EVENTS_FAILURE",
};
