export const userTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    LOGIN_USER_START: "LOGIN_USER_START",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
}