export const userTypes = {
    LOGIN_USER_START: "LOGIN_USER_START",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    REGISTER_USER_START: "REGISTER_USER_START",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
}